/**
 * FROZEN CONTRACT — do not edit this file.
 * The engine (src/engine/**) and the UI (src/ui/**, src/App.tsx) are built
 * against these types in parallel. Integration assumes them verbatim.
 */

// ---------- schema (baked in; users never pick a type) ----------
export type ColKind = 'date' | 'cat' | 'id' | 'int' | 'bool' | 'text';

export interface ColumnDef {
  name: string;          // column name in the parquet
  label: string;         // human label
  kind: ColKind;
  filterable: boolean;   // appears in the filter panel
  groupable: boolean;    // can be used as X / series / pivot dim / custom-category base
}

export const COLUMNS: ColumnDef[] = [
  { name: 'case_id',                 label: 'Case ID',                 kind: 'id',   filterable: false, groupable: false },
  { name: 'person_id',               label: 'Person ID',               kind: 'id',   filterable: false, groupable: false },
  { name: 'count',                   label: 'Count #',                 kind: 'int',  filterable: false, groupable: false },
  { name: 'charge_code',             label: 'Charge code',             kind: 'cat',  filterable: false, groupable: false },
  { name: 'charge_description',      label: 'Charge description',      kind: 'cat',  filterable: true,  groupable: false },
  { name: 'crime_type',              label: 'Crime type',              kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'court',                   label: 'Court',                   kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'filing_date',             label: 'Filing date',             kind: 'date', filterable: true,  groupable: true  },
  { name: 'offense_date',            label: 'Offense date',            kind: 'date', filterable: false, groupable: false },
  { name: 'race',                    label: 'Race',                    kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'sex',                     label: 'Sex',                     kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'agency',                  label: 'Arresting agency',        kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'icr',                     label: 'Incident # (ICR)',        kind: 'text', filterable: false, groupable: false },
  { name: 'filing_source',           label: 'Filing source file',      kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'disposition_date',        label: 'Disposition date',        kind: 'date', filterable: true,  groupable: true  },
  { name: 'disposition_code',        label: 'Disposition code',        kind: 'cat',  filterable: false, groupable: true  },
  { name: 'disposition_description', label: 'Disposition',             kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'disposition_reason',      label: 'Disposition reason',      kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'disposition_source',      label: 'Disposition source file', kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'case_status',             label: 'Case status',             kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'outcome_class',           label: 'Outcome class',           kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'prosecutorial_call',      label: 'Prosecutorial call',      kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'dtp_class',               label: 'Decline-to-prosecute list', kind: 'cat', filterable: true, groupable: true },
  { name: 'outcome_detail',          label: 'Outcome (detailed)',      kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'case_disposition_status', label: 'Case disposition status', kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'filed_in_window',         label: 'Filed in 2022-2025',      kind: 'bool', filterable: false, groupable: false },
  { name: 'disposed_in_window',      label: 'Disposed in 2022-2025',   kind: 'bool', filterable: false, groupable: false },
  { name: 'filed_under',             label: 'Filed under (DA)',        kind: 'cat',  filterable: true,  groupable: true  },
  { name: 'disposed_under',          label: 'Disposed under (DA)',     kind: 'cat',  filterable: true,  groupable: true  },
];

// ---------- lens: the cohort guard ----------
export type Lens = 'filings' | 'dispositions' | 'all';
export const LENS_INFO: Record<Lens, { label: string; dateField: string; windowFlag: string | null; blurb: string }> = {
  filings:      { label: 'Filings',      dateField: 'filing_date',      windowFlag: 'filed_in_window',
                  blurb: 'Charges entering the system, Jan 2022 - Dec 2025. Time axis = filing date.' },
  dispositions: { label: 'Dispositions', dateField: 'disposition_date', windowFlag: 'disposed_in_window',
                  blurb: 'Charges resolved, Jan 2022 - Dec 2025, including cases filed earlier. Time axis = disposition date.' },
  all:          { label: 'Both',         dateField: 'filing_date',      windowFlag: null,
                  blurb: 'Filed in the window, resolved in it, or both: every charge row. The filing-date axis reaches back to 2004 for backlog charges.' },
};

// ---------- measures ----------
export type Measure = 'charges' | 'cases' | 'people';
export const MEASURES: Record<Measure, string> = {
  charges: 'Charges', cases: 'Distinct cases', people: 'Distinct people',
};

// ---------- custom categories (user-defined groupings) ----------
export interface Bucket { name: string; values: string[] }
export interface Grouping {
  id: string;            // stable, e.g. 'g_1699...'
  name: string;          // e.g. 'Outcome family'
  column: string;        // base categorical column name
  buckets: Bucket[];     // a value appears in at most one bucket
  otherLabel: string;    // label for unassigned values, default 'Other'
}

// A dimension is either a raw column or a user grouping
export type Dim = { kind: 'col'; col: string } | { kind: 'grouping'; groupingId: string };

// ---------- view state (URL-serializable) ----------
export type ChartType = 'line' | 'bar' | 'stackedBar' | 'pctBar' | 'area' | 'heatmap' | 'pivot' | 'table';
export type Granularity = 'month' | 'quarter' | 'year';

export interface ViewState {
  lens: Lens;
  chart: ChartType;
  x: Dim | null;                    // for time charts: {kind:'col', col: <lens dateField>}
  series: Dim | null;               // color / stacking dimension
  granularity: Granularity;
  measure: Measure;
  pct: boolean;                     // show % instead of raw counts
  pctDenom: 'view' | 'lens';        // 'view' = share within filtered view; 'lens' = share of ALL lens rows per x
  filters: Record<string, string[]>; // col -> selected values (empty/absent = all); date cols excluded
  dateFrom: string | null;          // 'YYYY-MM-DD' applied to the lens date field
  dateTo: string | null;
}

export const DEFAULT_VIEW: ViewState = {
  lens: 'filings', chart: 'line', x: { kind: 'col', col: 'filing_date' }, series: null,
  granularity: 'month', measure: 'charges', pct: false, pctDenom: 'view', filters: {}, dateFrom: null, dateTo: null,
};

// ---------- engine API (implemented in src/engine/index.ts) ----------
export interface Dataset {
  rowCount: number;
  // categorical columns: dictionary + per-row codes (code -1 = null)
  cats: Record<string, { dict: string[]; codes: Int32Array }>;
  // date columns: days since epoch per row (NaN/-1e9 sentinel for null)
  dates: Record<string, Int32Array>;
  ids: Record<string, Int32Array>;   // case_id, person_id, count
  bools: Record<string, Uint8Array>; // filed_in_window, disposed_in_window
  text: Record<string, string[]>;    // charge_description, icr, charge_code
}

export interface AggRow { x: string; series: string | null; value: number }
export interface AggResult {
  rows: AggRow[];
  xOrder: string[];        // display order for x values
  seriesOrder: string[];   // display order for series values
  total: number;           // measure over the whole filtered set (for pct)
  filteredRowCount: number;
  /** Present when pct && pctDenom==='lens': x -> UNFILTERED measure total (lens window + dates only). */
  xBaseline?: Record<string, number>;
}

export interface Notice { level: 'warn' | 'info'; title: string; detail: string }

/**
 * Engine exports (src/engine/index.ts must export exactly these):
 *   loadDataset(url: string): Promise<Dataset>
 *   aggregate(ds: Dataset, view: ViewState, groupings: Grouping[]): AggResult
 *   distinctValues(ds: Dataset, col: string): string[]          // sorted, non-null
 *   noticesFor(view: ViewState, groupings: Grouping[]): Notice[]
 *   encodeView(view: ViewState): string                          // URL-hash safe
 *   decodeView(hash: string): ViewState | null
 *   loadGroupings(): Grouping[]                                  // localStorage
 *   saveGroupings(g: Grouping[]): void
 *   PRESET_GROUPINGS: Grouping[]                                 // shipped examples
 *   aggToCsv(r: AggResult, view: ViewState): string              // current view as CSV text
 */

// ---------- palette (validated reference; do not invent colors) ----------
export const PALETTE = {
  light: {
    surface: '#fcfcfb', page: '#f9f9f7', ink1: '#0b0b0b', ink2: '#52514e', ink3: '#898781',
    grid: '#e1e0d9', axis: '#c3c2b7',
    series: ['#2a78d6', '#eb6834', '#1baf7a', '#eda100', '#e87ba4', '#008300', '#4a3aa7', '#e34948'],
    seq: ['#cde2fb', '#9ec5f4', '#6da7ec', '#3987e5', '#256abf', '#1c5cab', '#104281', '#0d366b'],
    good: '#0ca30c', warn: '#fab219', crit: '#d03b3b',
  },
  dark: {
    surface: '#1a1a19', page: '#0d0d0d', ink1: '#ffffff', ink2: '#c3c2b7', ink3: '#898781',
    grid: '#2c2c2a', axis: '#383835',
    series: ['#3987e5', '#d95926', '#199e70', '#c98500', '#d55181', '#008300', '#9085e9', '#e66767'],
    seq: ['#0d366b', '#104281', '#184f95', '#256abf', '#3987e5', '#6da7ec', '#9ec5f4', '#cde2fb'],
    good: '#0ca30c', warn: '#fab219', crit: '#d03b3b',
  },
} as const;

// More than 8 series: fold the remainder into 'Other' (never cycle hues).
export const MAX_SERIES = 8;

export const DATA_URL: string =
  (import.meta as any).env?.VITE_DATA_URL || `${(import.meta as any).env?.BASE_URL || '/'}data/hayden.parquet`;
